---   #indicates the start of a yaml section
all:
  hosts:
    testsystem:
      remote_tmp: C:\Users\user\Tmp
      ansible_shell_typ: cmd
      ansible_connection: ssh
      ansible_host: 192.168.7.164
      ansible_user: user
      ansible_password: user
  children:
    windows10:
      hosts:
        testsystem:
        
